[2024-01-04T12:17:16.604+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T04:46:00+00:00 [queued]>
[2024-01-04T12:17:16.636+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T04:46:00+00:00 [queued]>
[2024-01-04T12:17:16.637+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:17:16.685+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_product_returns> on 2024-01-04 04:46:00+00:00
[2024-01-04T12:17:16.693+0000] {standard_task_runner.py:57} INFO - Started process 186 to run task
[2024-01-04T12:17:16.700+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_product_returns', 'scheduled__2024-01-04T04:46:00+00:00', '--job-id', '464', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmp9wfi3006']
[2024-01-04T12:17:16.702+0000] {standard_task_runner.py:85} INFO - Job 464: Subtask insert_into_product_returns
[2024-01-04T12:17:16.810+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T04:46:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:17:17.006+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_product_returns' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T04:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T04:46:00+00:00'
[2024-01-04T12:17:17.008+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;
[2024-01-04T12:17:17.027+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:17:17.050+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:17:17.164+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;, parameters: None
[2024-01-04T12:17:17.170+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:17:17.202+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_product_returns, execution_date=20240104T044600, start_date=20240104T121716, end_date=20240104T121717
[2024-01-04T12:17:17.274+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:17:17.322+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
